from app.domain.schemas import AgentAccuracyLevel
from app.services.solution_orchestrator import SolutionOrchestrator
from app.services.ai_agent_blueprint import AiAgentBlueprintService
from app.services.architecture import ArchitectureService


def test_generates_nagare_sharepoint_sap_solution() -> None:
    text = """
    Nagare JIT process receives production sequence from SAP.
    SharePoint stores SOP documents.
    Supplier call-offs are generated by lead time and delivery window.
    Warehouse validates ASN and line feeding confirms sequence consumption.
    AI agent should answer questions with embeddings and citations.
    """

    solution = SolutionOrchestrator().generate("nagare-sop.txt", text)

    assert solution.source_name == "nagare-sop.txt"
    assert len(solution.functional_requirements) >= 7
    assert solution.nagare_rules is not None
    assert any(item.integration_type == "SharePoint" for item in solution.integration_design)
    assert any(item.integration_type == "SAP OData" for item in solution.integration_design)
    assert any(entity.name == "sequence_calloff" for entity in solution.database.entities)
    assert "erDiagram" in solution.database.er_diagram_mermaid
    assert solution.accuracy_profile.level == AgentAccuracyLevel.BALANCED


def test_generates_baseline_solution_for_generic_brd() -> None:
    text = """
    The current process uses manual approval, spreadsheet tracking, and repeated email handoffs.
    The target workflow must generate requirements, APIs, database design, UI design, and tests.
    Pain points include delay, errors, and unclear ownership.
    """

    solution = SolutionOrchestrator().generate("brd.txt", text)

    assert solution.executive_summary
    assert len(solution.functional_requirements) == 4
    assert solution.nagare_rules is None
    assert len(solution.non_functional_requirements) == 6
    assert solution.architecture.frontend


def test_audit_accuracy_level_adds_review_gates() -> None:
    text = """
    SAP Nagare JIT process with supplier call-offs, sequence delivery windows,
    SharePoint source documents, approval workflow, KPIs, validation rules, and audit export.
    """

    solution = SolutionOrchestrator().generate(
        "audit-nagare.txt",
        text,
        accuracy_level=AgentAccuracyLevel.AUDIT,
    )

    assert solution.accuracy_profile.level == AgentAccuracyLevel.AUDIT
    assert solution.accuracy_profile.review_required is True
    assert solution.accuracy_profile.target_confidence == 0.95
    assert any("Block export" in rule for rule in solution.accuracy_profile.escalation_rules)
    assert any(test.test_id == "UAT-004" for test in solution.test_cases)
    assert any(risk.risk_id == "R-006" for risk in solution.risk_analysis)


def test_architecture_aws_branch_and_agent_blueprint() -> None:
    architecture = ArchitectureService().design("AWS alternative with SAP agent embeddings")
    code = AiAgentBlueprintService().langgraph_code()

    assert any("AWS alternative" in item for item in architecture.cloud)
    assert "StateGraph" in code
